import { Game } from './game';

export const GAMES: Game[] = [
  {
    id: 10,
    name: 'Final Fantasy XV',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'fantasy',
    thumbRating: 5,
  },
  {
    id: 9,
    name: 'Final Fantasy V111',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'fantasy',
    thumbRating: 5,
  },
  {
    id: 8,
    name: 'Kingdom of Hearts 111',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'romance',
    thumbRating: 5,
  },
  {
    id: 7,
    name: 'Collection of Manna',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'romance',
    thumbRating: 5,
  },
  {
    id: 6,
    name: 'Dragon Quest Builders2',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'sci-fi',
    thumbRating: 5,
  },
  {
    id: 5,
    name: 'Tactics Ogre. let us Cling together',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'horror',
    thumbRating: 5,
  },
  {
    id: 4,
    name: 'Nier : Automata',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'scary',
    thumbRating: 5,
  },
  {
    id: 3,
    name: 'Final Fantasy X1V : Stormblood',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'fantasy',
    thumbRating: 5,
  },
  {
    id: 2,
    name: 'Deus Ex: Human Revolution',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'sci-fi',
    thumbRating: 5,
  },
  {
    id: 1,
    name: 'Final Fantasy XIV: Shadowbringers',
    imageUrl: 'assets/shadowBringers.jpg',
    platform: 'windows',
    releaseDate: '11/01/2001',
    genre: 'fantasy',
    thumbRating: 5,
  },
];
